//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvConvert.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvConvert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SequenceStarted,Conversion started.
        ///FileStarted,  Processing {0}...
        ///SequenceDone,All files have been processed.
        ///FileDone,  Done, saved to {0}.
        ///GeneralError,      Error: {0}
        ///GeneralWarning,      Warn: {0}
        ///GeneralInfo,      Info: {0}
        ///Reading,    Reading...
        ///OptimizingObject,    Optimizing object...
        ///OptimizingMaterial,    Merging materials...
        ///PreProcessing,    Pre-processing...
        ///PostProcessing,    Post-processing...
        ///Writing,    Exporting...
        ///Dimension,      Size: {0}
        ///TextureHint,      Texture: {0}
        ///ObjectNotReadab [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SequenceStarted,转换已开始。
        ///FileStarted,  正在处理 {0}…
        ///SequenceDone,所有文件都已转换完成。
        ///FileDone,  完成，已保存至 {0}。
        ///GeneralError,      错误: {0}
        ///GeneralWarning,      警告: {0}
        ///GeneralInfo,      消息: {0}
        ///Reading,    正在读入…
        ///OptimizingObject,    正在简化模型结构…
        ///OptimizingMaterial,    正在合并重复材质…
        ///PreProcessing,    正在预处理…
        ///PostProcessing,    正在后期处理…
        ///Writing,    正在导出…
        ///Dimension,      物件尺寸: {0}
        ///TextureHint,      贴图文件: {0}
        ///ObjectNotReadable,    错误: 无法读入物件
        ///
        ///MainForm,CSV模型转换工具
        ///groupBoxCredit,作者
        ///
        ///groupBoxMisc,杂项
        ///labelRound,小数位数
        ///labelRoundV,顶点:
        ///la [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_zh_CHS {
            get {
                return ResourceManager.GetString("lang_zh_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SequenceStarted,轉換已開始。
        ///FileStarted,  正在處理 {0}…
        ///SequenceDone,所有檔都已轉換完成。
        ///FileDone,  完成，已保存至 {0}。
        ///GeneralError,      錯誤: {0}
        ///GeneralWarning,      警告: {0}
        ///GeneralInfo,      消息: {0}
        ///Reading,    正在讀入…
        ///OptimizingObject,    正在簡化模型結構…
        ///OptimizingMaterial,    正在合併重複材質…
        ///PreProcessing,    正在預處理…
        ///PostProcessing,    正在後期處理…
        ///Writing,    正在匯出…
        ///Dimension,      物件尺寸: {0}
        ///TextureHint,      貼圖文件: {0}
        ///ObjectNotReadable,    錯誤: 無法讀入物件
        ///
        ///MainForm,CSV模型轉換工具
        ///groupBoxCredit,作者
        ///
        ///groupBoxMisc,雜項
        ///labelRound,小數位數
        ///lab [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string lang_zh_CHT {
            get {
                return ResourceManager.GetString("lang_zh_CHT", resourceCulture);
            }
        }
    }
}
